/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
/** ID lister. */
package src.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 8;
  /** RegularExpression Id. */
  int FLOAT = 9;
  /** RegularExpression Id. */
  int Num = 10;
  /** RegularExpression Id. */
  int BOOL = 11;
  /** RegularExpression Id. */
  int ARR = 12;
  /** RegularExpression Id. */
  int STRUCT = 13;
  /** RegularExpression Id. */
  int ARROWRIGHT = 14;
  /** RegularExpression Id. */
  int ARROWLEFT = 15;
  /** RegularExpression Id. */
  int QUOTE = 16;
  /** RegularExpression Id. */
  int PLUS = 17;
  /** RegularExpression Id. */
  int MINUS = 18;
  /** RegularExpression Id. */
  int TIMES = 19;
  /** RegularExpression Id. */
  int MOD = 20;
  /** RegularExpression Id. */
  int POW = 21;
  /** RegularExpression Id. */
  int DIV = 22;
  /** RegularExpression Id. */
  int LPAR = 23;
  /** RegularExpression Id. */
  int RPAR = 24;
  /** RegularExpression Id. */
  int LBRACKET = 25;
  /** RegularExpression Id. */
  int RBRACKET = 26;
  /** RegularExpression Id. */
  int LSBRACKET = 27;
  /** RegularExpression Id. */
  int RSBRACKET = 28;
  /** RegularExpression Id. */
  int LET = 29;
  /** RegularExpression Id. */
  int MUT = 30;
  /** RegularExpression Id. */
  int EQ = 31;
  /** RegularExpression Id. */
  int EQREL = 32;
  /** RegularExpression Id. */
  int SEMCOL = 33;
  /** RegularExpression Id. */
  int COMMA = 34;
  /** RegularExpression Id. */
  int DOT = 35;
  /** RegularExpression Id. */
  int IF = 36;
  /** RegularExpression Id. */
  int ELIF = 37;
  /** RegularExpression Id. */
  int ELSE = 38;
  /** RegularExpression Id. */
  int MATCH = 39;
  /** RegularExpression Id. */
  int VB = 40;
  /** RegularExpression Id. */
  int WHILE = 41;
  /** RegularExpression Id. */
  int FOR = 42;
  /** RegularExpression Id. */
  int IN = 43;
  /** RegularExpression Id. */
  int TO = 44;
  /** RegularExpression Id. */
  int DDOT = 45;
  /** RegularExpression Id. */
  int DEFAULTCASE = 46;
  /** RegularExpression Id. */
  int GT = 47;
  /** RegularExpression Id. */
  int GEQT = 48;
  /** RegularExpression Id. */
  int LT = 49;
  /** RegularExpression Id. */
  int LEQT = 50;
  /** RegularExpression Id. */
  int DIFF = 51;
  /** RegularExpression Id. */
  int NOT = 52;
  /** RegularExpression Id. */
  int AND = 53;
  /** RegularExpression Id. */
  int OR = 54;
  /** RegularExpression Id. */
  int XOR = 55;
  /** RegularExpression Id. */
  int NEW = 56;
  /** RegularExpression Id. */
  int REF = 57;
  /** RegularExpression Id. */
  int FUN = 58;
  /** RegularExpression Id. */
  int MAIN = 59;
  /** RegularExpression Id. */
  int LEN = 60;
  /** RegularExpression Id. */
  int PRINT = 61;
  /** RegularExpression Id. */
  int PRINTLN = 62;
  /** RegularExpression Id. */
  int PRINTF = 63;
  /** RegularExpression Id. */
  int EXIT = 64;
  /** RegularExpression Id. */
  int STR = 65;
  /** RegularExpression Id. */
  int Id = 66;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 7>",
    "<INT>",
    "<FLOAT>",
    "<Num>",
    "<BOOL>",
    "\"arr\"",
    "\"struct\"",
    "\"->\"",
    "\"<-\"",
    "\"\\\'\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"%\"",
    "\"^\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"let\"",
    "\"mut\"",
    "\"=\"",
    "\"==\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"if\"",
    "\"elif\"",
    "\"else\"",
    "\"match\"",
    "\"|\"",
    "\"while\"",
    "\"for\"",
    "\"in\"",
    "\"to\"",
    "\":\"",
    "\"_\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"!=\"",
    "\"!\"",
    "\"and\"",
    "\"or\"",
    "\"xor\"",
    "\"new\"",
    "\"val\"",
    "\"fn\"",
    "\"main\"",
    "\"#\"",
    "\"print\"",
    "\"println\"",
    "\"printf\"",
    "\"exit\"",
    "<STR>",
    "<Id>",
  };

}
