/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
/** ID lister. */
package src.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 5;
  /** RegularExpression Id. */
  int FLOAT = 6;
  /** RegularExpression Id. */
  int Num = 7;
  /** RegularExpression Id. */
  int BOOL = 8;
  /** RegularExpression Id. */
  int SETVAL = 9;
  /** RegularExpression Id. */
  int GETVAL = 10;
  /** RegularExpression Id. */
  int QUOTE = 11;
  /** RegularExpression Id. */
  int PLUS = 12;
  /** RegularExpression Id. */
  int MINUS = 13;
  /** RegularExpression Id. */
  int TIMES = 14;
  /** RegularExpression Id. */
  int MOD = 15;
  /** RegularExpression Id. */
  int POW = 16;
  /** RegularExpression Id. */
  int DIV = 17;
  /** RegularExpression Id. */
  int LPAR = 18;
  /** RegularExpression Id. */
  int RPAR = 19;
  /** RegularExpression Id. */
  int LBRACKET = 20;
  /** RegularExpression Id. */
  int RBRACKET = 21;
  /** RegularExpression Id. */
  int LSBRACKET = 22;
  /** RegularExpression Id. */
  int RSBRACKET = 23;
  /** RegularExpression Id. */
  int LET = 24;
  /** RegularExpression Id. */
  int MUT = 25;
  /** RegularExpression Id. */
  int EQ = 26;
  /** RegularExpression Id. */
  int SEMCOL = 27;
  /** RegularExpression Id. */
  int COMMA = 28;
  /** RegularExpression Id. */
  int DOT = 29;
  /** RegularExpression Id. */
  int IF = 30;
  /** RegularExpression Id. */
  int ELIF = 31;
  /** RegularExpression Id. */
  int ELSE = 32;
  /** RegularExpression Id. */
  int MATCH = 33;
  /** RegularExpression Id. */
  int WHILE = 34;
  /** RegularExpression Id. */
  int DDOT = 35;
  /** RegularExpression Id. */
  int DEFAULTCASE = 36;
  /** RegularExpression Id. */
  int GT = 37;
  /** RegularExpression Id. */
  int GEQT = 38;
  /** RegularExpression Id. */
  int LT = 39;
  /** RegularExpression Id. */
  int LEQT = 40;
  /** RegularExpression Id. */
  int DIFF = 41;
  /** RegularExpression Id. */
  int NOT = 42;
  /** RegularExpression Id. */
  int AND = 43;
  /** RegularExpression Id. */
  int OR = 44;
  /** RegularExpression Id. */
  int NEW = 45;
  /** RegularExpression Id. */
  int REF = 46;
  /** RegularExpression Id. */
  int LEN = 47;
  /** RegularExpression Id. */
  int PRINT = 48;
  /** RegularExpression Id. */
  int PRINTLN = 49;
  /** RegularExpression Id. */
  int EXIT = 50;
  /** RegularExpression Id. */
  int Id = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<INT>",
    "<FLOAT>",
    "<Num>",
    "<BOOL>",
    "\"->\"",
    "\"<-\"",
    "\"\\\'\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"%\"",
    "\"^\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"let\"",
    "\"mut\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"if\"",
    "\"elif\"",
    "\"else\"",
    "\"match\"",
    "\"while\"",
    "\":\"",
    "\"_\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"!=\"",
    "\"!\"",
    "\"and\"",
    "\"or\"",
    "\"new\"",
    "\"val\"",
    "\"#\"",
    "\"print\"",
    "\"println\"",
    "\"exit\"",
    "<Id>",
  };

}
